### PR TITLE
README: fix alfredworklow file name

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by xilopaint** [comment]
haha It's another workflow of mine. Thanks for the PR!

**Comment by vitorgalvao** [comment]
> haha It's another workflow of mine.

I also copy and paste READMEs between similar projects.

**Comment by xilopaint** [comment]
Now I see you added a nonexistent dot on the filename. :(

**Comment by vitorgalvao** [comment]
> Now I see you added a nonexistent dot on the filename.

On the contrary, the dot is there on the filename (but maybe you didn’t want to include it?). Check the releases page.

**Comment by xilopaint** [comment]
Weird, it was added automatically by GitHub not by me. I uploaded the file that you can see on the repo but GitHub releases seemingly don't admit spaces.

**Pull request merged**
